export const ROUTES = {
  Splash: 'Splash',
  GetStarted: 'GetStarted',
  Login: 'Login',
  Register: 'Register',
  OTPVerification: 'OTPVerification',
  RoleSelection: 'RoleSelection',
  ProfileCompletion: 'ProfileCompletion',
  ForgotPassword: 'ForgotPassword',
  AppTabs: 'AppTabs',
  Home: 'Home',
  ProductListing: 'ProductListing',
  ProductDetails: 'ProductDetails',
  SellerStore: 'SellerStore',
  Search: 'Search',
  Messages: 'Messages',
  ConversationThread: 'ConversationThread',
  Profile: 'Profile',
  MyOrders: 'MyOrders',
  OrderDetails: 'OrderDetails',
  MyAddresses: 'MyAddresses',
  Settings: 'Settings',
  SupportHelp: 'SupportHelp',
  Cart: 'Cart',
  Checkout: 'Checkout',
} as const;
